FileApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="file"
urlpatterns = [
    path('file_list/<int:project_id>', views.show_file_list, name="file_list"),
    # path('upload/', views.show_upload, name="upload"),
    # path('form_create_new_file/', views.form_create_new_file, name="form_create_new_file"),
    # path('create_new_file/', views.create_new_file, name="create_new_file"),
]

FromNode/urls.py
from django.contrib import admin
from django.urls import path, include
from ProjectApp import views
from FileApp import views
from NodeApp import views
from UserApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainApp.urls')),
    path('project/', include('ProjectApp.urls')),
    path('file/',include('FileApp.urls')),
    path('node/', include('NodeApp.urls')),
    path('user/', include('UserApp.urls')),
]

NodeApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'node'
urlpatterns = [
    path('version_all/<int:file_Code>', views.version_all, name="version_all"),
    path('node_detail/<str:node_Code>', views.node_detail, name="node_detail"),
    path('upload/', views.Upload, name="upload"),
]
if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

NodeApp/models.py
from django.db import models
from django.contrib.auth.models import User

class Nodes(models.Model):
    Code = models.CharField(primary_key = True, max_length=255, default=0, unique=True) #노드별 고유 코드
    createdDate = models.DateTimeField(auto_now=True)
    fileObj = models.FileField(upload_to="media", blank=False) #이 노드에 저장되어 있는 파일
    previousCode = models.ForeignKey('self',on_delete=models.SET_NULL, null=True, blank=True) #이전 노드
    ownerPCode = models.ForeignKey('ProjectApp.projects', on_delete=models.CASCADE)#이 노드가 속해 있는 프로젝트
    ownerFCode = models.ForeignKey('FileApp.Files', on_delete=models.CASCADE)#이 노드가 속해 있는 프로젝트
    whoIsOwner = models.ForeignKey(User,on_delete = models.SET_NULL, null=True, blank=True)#이 노드를 만든 회원
    
class TestNode(models.Model):
    file = models.FileField(upload_to="test")

NodeApp/views.py
from django.shortcuts import render, redirect
from .models import Nodes, TestNode
from FileApp.models import Files
from ProjectApp.models import Projects
from django.contrib.auth.models import User
from datetime import datetime

def version_all(request,file_Code):
    The_File = Files.objects.get(Code=file_Code)
    A = Nodes.objects.all()
    node_objs =[]
    for x in A:
        if x.ownerFCode.Code == The_File.Code:
            node_objs.append(x)
    return render(request, 'NodeApp/node_list.html',{'node_objs':node_objs})


def node_detail(request,node_Code):
    node_obj = Nodes.objects.filter(Code = node_Code)
    return render(request, 'NodeApp/node_details.html', {'node_obj':node_obj})

def Upload(request):
    '''
    nodes = TestNode()
    if (request.method == 'POST'):
        for files in request.FILES.getlist('myFile'):
            nodes.file = files
            nodes.save()
    else :
        pass
    '''

    nodeobj = Nodes()
    nodeobj.Code = "001000"
    nodeobj.createdDate = datetime.now
    for files in request.FILES.getlist('myFile'):
         nodeobj.fileObj = files
    nodeobj.previousCode =Nodes.objects.get(Code="000001") 
    nodeobj.ownerPCode = Projects.objects.get(Code="000001")
    nodeobj.whoIsOwner = User.objects.get(username = 'sea')
    nodeobj.save()
    
    return render(request, 'NodeApp/version_all.html')
        

NodeApp/templates/NodeApp/node_details.html
{% extends 'base.html' %}
{% load sass_tags %}
{% load static %}

{% block scss %}
    <link href="{% sass_src 'NodeApp/CSS/Upload.scss' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block content %}
<h1>노드 상세내용 - 페이지번호 : 08</h1>


{% for x in node_obj %}
{{x.Code}}<br>
{{x.fileObj}}<br>
{{x.whoIsOwner}}<br>
{{x.createdDate}}
{% endfor %}

{% endblock %}
{% block JS %}
{% endblock %}

NodeApp/templates/NodeApp/node_list.html
{% extends 'base.html' %}
{% load sass_tags %}
{% load static %}

{% block scss %}
    <link href="{% sass_src 'NodeApp/CSS/Upload.scss' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block content %}
<h1>파일 상세내용 - 페이지번호 : 07</h1>
<h1>여기가 바로 '그 트리' 가 등장해야 할 곳</h1>

{% for node in node_objs%}
<a href="{% url 'node:node_detail' node.Code %}">{{node.Code}}</a><br>


{% endfor %}
{{empty}}
{% endblock %}
{% block JS %}
{% endblock %}

NodeApp/templates/NodeApp/test.html
{% load sass_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="{% sass_src 'NodeApp/CSS/test.scss' %}" rel="stylesheet" type="text/css">
</head>
<body>
    
    <div class="drop-zone">
        <!-- form 으로 전체를 담아서 input submit을 하면 되지 않을까? -->
        <span class="drop-zone__prompt">drop-zone</span>
        <!-- <div class="drop-zone__thumb" data-label="myfile.txt">

        </div> -->
        <input type="file" name="myFile" class="drop-zone__input" multiple>
    </div>
    <script src="{% static 'NodeApp/JS/Upload.js' %}"></script>
</body>
</html>

NodeApp/templates/NodeApp/upload.html
{% extends 'base.html' %}
{% load sass_tags %}
{% block body %}
    <button>파일열기</button>
    <form>커밋메세지</form>
    <button>제출</button>
    <button><a href="{% url 'show_project' %}">프로젝트 리스트로 돌아가기</a></button>
{% endblock %}