FileApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="file"
urlpatterns = [
    path('file_list/<int:project_id>', views.show_file_list, name="file_list"),
    # path('upload/', views.show_upload, name="upload"),
    # path('form_create_new_file/', views.form_create_new_file, name="form_create_new_file"),
    # path('create_new_file/', views.create_new_file, name="create_new_file"),
]

FromNode/urls.py
from django.contrib import admin
from django.urls import path, include
from ProjectApp import views
from FileApp import views
from NodeApp import views
from UserApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainApp.urls')),
    path('project/', include('ProjectApp.urls')),
    path('file/',include('FileApp.urls')),
    path('node/', include('NodeApp.urls')),
    path('user/', include('UserApp.urls')),
]

ProjectApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'project'
urlpatterns = [
    path('project_list/', views.show_project_list, name="project_list"),
    path('project_detail/', views.show_project_detail, name="project_detail"),
    path('project_checkcode/',views.project_checkcode, name='project_checkcode'),

    # path('form_create_project/', views.form_create_project, name="form_create_project"),
    # path('create_project/', views.create_project, name="create_project"),
]

UserApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'user'
urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('mypage/',views.mypage,name='mypage'),
    path('logout/',views.logout,name='logout'),
]

ProjectApp/models.py
from django.db import models
from django.contrib.auth.models import User
from random import choice
import string

def random_code():
    arr = [choice(string.ascii_letters) for _ in range(8)]
    Code = ''.join(arr)
    return Code

class Projects(models.Model):
    Code = models.CharField(max_length=255,default=random_code, unique=True)
    name = models.CharField(max_length=255)
    whoIsOwner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

ProjectApp/views.py
from django.shortcuts import render, redirect
from .models import Projects
from django.contrib.auth.models import User
from django.contrib import auth
from UserApp.models import Profile
import random
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from notifications.signals import notify

# User 모델 불러오기
# 불러온 User 모델의 Projects 불러오기
# 불러온 Projects를 슬라이싱, 이후 이걸 포함하는지 아닌지 대조!

def show_project_list(request):
    proj_obj = []
    User_Profile = []
    User_Projects = []
    empty = ''
    if request.user.is_authenticated:
        User_Profile = Profile.objects.get(user=request.user)
        # filter는 쿼리셋 메소드를 가져오니까 get으로 값을 불러오세요!!!!!!
        User_Projects = User_Profile.projects.split(',')
    else:
        pass


    for i in User_Projects:
        proj_obj += Projects.objects.filter(name=i)
    if len(proj_obj) == 0:
        empty = '참여중인 프로젝트가 없습니다'
    return render(request, 'ProjectApp/project_list.html', {'proj_obj' : proj_obj,'empty':empty})

def show_project_detail(request):
    # project에 소속된 file들이 보여지는 detail화면으로 슝 !
    return render(request, 'FileApp/file_list.html')

def project_checkcode(request):
    Project = Projects.objects.all()
    Project_Codes = []
    for i in Project:
        Project_Codes.append(i.Code)
    if request.POST['Code'] in Project_Codes:
        Join_Project = Projects.objects.get(Code=request.POST['Code'])
        #이후는 알림 기능 배우고! Owner_User = User.objects.get(Username=Join_Project.whoIsOwner)
        message = Join_Project.name,"프로젝트에 대한 참가 요청이 전송되었습니다!"
    else:
        message = "해당 코드를 지닌 프로젝트가 존재하지 않습니다"

    proj_obj = []
    User_Profile = Profile.objects.get(user=request.user)
    # filter는 쿼리셋 메소드를 가져오니까 get으로 값을 불러오세요!!!!!!
    User_Projects = User_Profile.projects.split(',')

    for i in User_Projects:
        proj_obj += Projects.objects.filter(name=i)

    return render(request, 'ProjectApp/project_list.html', {'proj_obj' : proj_obj,'message': message})
# def form_create_project(request):
#     return render(request,'ProjectApp/form_create_project.html')


# def create_project(request):
#     proj_obj = Projects()
#     proj_obj.Code = random.randint(0,0xffffff)
#     proj_obj.name = request.GET['projectName']
#     proj_obj.whoIsOwner = User.objects.get(username = 'sea')
#     proj_obj.save()
#     return redirect('project_list')

def create_project(request):
    proj_obj = Projects()
    proj_obj.Code = random.randint(0,0xffffff)
    proj_obj.name = request.GET['projectName']
    proj_obj.whoIsOwner = User.objects.get(username = 'sea')
    proj_obj.save()
    return redirect('project_list')

# def logout(request):
#     auth.logout(request)s
#     return redirect('/')

ProjectApp/templates/ProjectApp/form_create_project.html
<!-- {% extends 'base.html' %}
{% load sass_tags %}
{% block body %}
<button><a href="{ url 'show_project' }">프로젝트 리스트로 가기</a></button>
    <form action= "{ url 'create_project' }">
        프로젝트 이름<br>
        <input type="text" size="15" name="projectName"/><br/>
        <input type="submit" id="btn" value="생성하기"/>
    </form>
    {% endblock %} -->

    hi

ProjectApp/templates/ProjectApp/project_list.html
{% extends 'base.html' %}
{% load sass_tags %}
{% block content %}
{% if user.is_authenticated %}
<h1>프로젝트 리스트 - 페이지번호 : 04</h1>
    {% for project in proj_obj %}
    <button><a href="{% url 'file:file_list' project.id %}">{{project.name}}</a></button><br>
    
    {% endfor %}
    {{empty}}
    <!-- <button><a href="{ url 'form_create_project' }">프로젝트 만들기</a></button> -->
    <form action="{% url 'project:project_checkcode' %}" method='POST'>
        {% csrf_token %}
        <p>다른 프로젝트 참여하기</p>
        <input type="text" name = 'Code'>
        <button type="submit">시작하기</button>
    </form>
    {% for message in message%}
        {{message}}
    {% endfor %}
<button><a href = "{% url 'user:logout' %}">로그아웃</a></button>
{% else %}
<h1>회원가입 페이지 - 페이지번호는 몰라</h1>
<button><a href = "{% url 'user:signup' %}">회원가입하기</a></button>
<button><a href = "{% url 'user:login' %}">로그인하기</a></button>
{% endif %}
{% endblock %}